config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def create
    @article = Article.new(params[:article])
    @article.save
    redirect_to article_path(@article)
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(restaurant_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to article_path
  end
end

private

def article_params
  params.require(:article).permit(:title, :content)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_for(@article) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<!-- url: articles_path -->

app/views/articles/index.html.erb
<h1> Index </h1>
<p>Add a navbar</p>
<br>
<ul>
  <% @articles.each do |article| %>
  <li> <%= link_to article.title, article_path(article) %> </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<%= form_for(@article) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<!-- url: articles_path -->

app/views/articles/show.html.erb
<h2>Is this the specific article you are looking for?</h2>

<h2> <%= @article.title %> </h2>
<p> %= @article.content %> </p>

<div>
<%= link_to "Delete the article: #{@article.title}?",
            article_path(@article),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
</div>
<br>
<div>
<%= link_to "Edit the article: #{@article.title}?", edit_article_path(@article) %>
</div>

<!-- Normal HTML command:
<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/article/2">
  Delete the article
</a>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>